development: &default
  adapter: postgresql
  database: jenny-rails_development
  encoding: utf8
  host: localhost
  min_messages: warning
  pool: 2
  timeout: 5000

test:
  <<: *default
  database: jenny-rails_test

production:
  <<: *default
  database: jenny-rails_production
